# Determines if we search the title (optional). Defaults to true.
matchTitle: false

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: true

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  "- Bug Report": bug
  "- Bugfix Pull Request": bug
  "- Feature Idea": feature
  "- Feature Pull Request": feature
  "- Documentation Report": documentation
  "- Docs Pull Request": documentation
  "- New Module Pull Request": new_module
  "- New Plugin Pull Request": new_plugin
  "- Refactoring Pull Request": refactor
  "- Test Pull Request": testing
  "Fixes #": has_issue