needs_triage:
- changed-files:
  - any-glob-to-any-file: '**'

tests:
- changed-files:
  - any-glob-to-any-file: 'tests/**'

docs_fragments:
- changed-files:
  - any-glob-to-any-file: 'changelogs/fragments/*'

plugin:
- changed-files:
  - any-glob-to-any-file: 'plugins/**'

module:
- changed-files:
  - any-glob-to-any-file: 'plugins/modules/*'

module_utils:
- changed-files:
  - any-glob-to-any-file: 'plugins/module_utils/*'

documentation:
- changed-files:
  - any-glob-to-any-file: '*.md'

github_actions:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/*'
