---
name: Lint GitHub Action
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - stable-*
  pull_request:
    paths:
      - '/.github/workflows/**'
  # Run CI once per day (at 06:00 UTC)
  schedule:
    - cron: '0 6 * * *'

jobs:
  workflow:
    name: Lint GitHub Workflow
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: actionlint
        id: actionlint  #optional, id required only when outputs are used in the workflow steps later
        uses: raven-actions/actionlint@v2
        with:
          matcher: false  # optional
          cache: false  # optional
          fail-on-error: true  # optional
          flags: "-ignore SC2086"  # optional

      - name: actionlint Summary
        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
          exit ${{ steps.actionlint.outputs.exit-code }}